<?php

$profiles = $debugWidget->getProfiler()->getProfiles();
$profiles = !$profiles? array() : $profiles;

$dbs = $debugWidget->getServices('db');

?>

<div id='pdw-panel-db' class='pdw-panel db'>
    <div class='title'>
        <h2>Database <a class='pdw-panel-close' id="phalcon-debugger-close-db-tab">&times;</a></h2>
    </div>
    <div class='panel-content'>
        <?php foreach ($dbs as $dbName) : ?>
            <?php

            $db = $debugWidget->getDI()->get($dbName);
            $descriptors = $db->getDescriptor();

            ?>

            <h3 class='collapser'>DB Server</h3>

            <table class='pdw-data-table'>
                <tr>
                    <td>Type</td>
                    <td><?php echo $db->getType(); ?></td>
                </tr>
                <?php foreach($descriptors as $k => $v) : ?>
                    <tr>
                        <td><?= $k; ?></td>
                        <td>
                            <?php

                            if (is_string($v)) {
                                if ($k != "password") {
                                    echo $v;
                                } else {
                                    echo '********';
                                }
                            } else {
                                echo '<pre> ' . var_dump($v) . '</pre>';
                            }

                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endforeach; ?>

        <h3 class='collapser'>SQL Queries</h3>

        <table class='pdw-sql-data-table'>
            <?php

            $total = 0;

            foreach ($profiles as $profile):
                $time = $profile->getTotalElapsedSeconds();
                $total += $time;

                $sql = $profile->getSQLStatement();
                $sqlVars = $profile->getSQLVariables();

                // Bind the values to the queries
                if (is_array($sqlVars)) {
                    foreach ($profile->getSQLVariables() as $key => $value) {
                        if (!strstr($key, ':')) $key = ':' . $key;

                        $sql = str_replace($key, $value, $sql);
                    }
                }

                ?>
                <tr>
                    <td>
                        <?= SqlFormatter::format($sql, true); ?>
                        <span class="execution-time-summary">&#8593; <strong>Execution time</strong> <?= round($time, 6); ?>s</span>
                    </td>
                </tr>

            <?php endforeach; ?>
            <tr>
                <td><span class="execution-time-summary">&#8721; <strong>Total</strong> <?php echo round($total, 6); ?>s</span></td>
            </tr>
        </table>
    </div><!-- End panel content -->
</div><!-- End pdw panel -->
