<div id='pdw-panel-request' class='pdw-panel request'>
    <div class='title'>
        <h2>Request <a class='pdw-panel-close' id="phalcon-debugger-close-request-tab">&times;</a></h2>
    </div>
    <div class='panel-content'>
        <?php if (isset($_SESSION) && !empty($_SESSION)) : ?>
            <h3 class='collapser'>$_SESSION</h3>

            <table class='pdw-data-table'>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                <?php foreach ($_SESSION as $key => $value) : ?>
                    <?php if ($key != '$PMM$') : ?>
                        <tr>
                            <td valign="top" width="10%"><?= $key; ?></td>
                            <td><?php var_dump($value); ?></td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>

        <h3 class='collapser'>$_COOKIE</h3>

        <table class='pdw-data-table'>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
            <?php if (isset($_COOKIE)) : ?>
                <?php foreach ($_COOKIE as $key => $value) : ?>
                    <tr>
                        <td valign="top" width="10%"><?= $key; ?></td>
                        <td><?php var_dump($value); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>

        <h3 class='collapser'>$_GET</h3>

        <table class='pdw-data-table'>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
            <?php if (isset($_GET)) : ?>
                <?php foreach ($_GET as $key => $value) : ?>
                    <tr>
                        <td valign="top" width="10%"><?= $key; ?></td>
                        <td><?php var_dump($value); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>

        <?php if (isset($_POST) && !empty($_POST)) : ?>
            <h3 class='collapser'>$_POST</h3>

            <table class='pdw-data-table'>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                <?php foreach ($_POST as $key => $value) : ?>
                    <tr>
                        <td valign="top" width="10%"><?= $key; ?></td>
                        <td><?php var_dump($value); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>

        <?php if (isset($_FILES) && !empty($_FILES)) : ?>
            <h3 class='collapser'>$_FILES</h3>

            <table class='pdw-data-table'>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                <?php foreach ($_FILES as $key => $value) : ?>
                    <tr>
                        <td valign="top" width="10%"><?= $key; ?></td>
                        <td><?php var_dump($value); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>

        <h3 class='collapser'>$_REQUEST</h3>

        <table class='pdw-data-table'>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
            <?php if (isset($_REQUEST)) : ?>
                <?php foreach ($_REQUEST as $key => $value) : ?>
                    <tr>
                        <td valign="top" width="10%"><?= $key; ?></td>
                        <td><?php var_dump($value); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>

        <?php if (isset($_ENV) && !empty($_ENV)) : ?>
            <h3 class='collapser'>$_ENV</h3>

            <table class='pdw-data-table'>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                    <?php foreach ($_ENV as $key => $value) : ?>
                        <tr>
                            <td valign="top" width="10%"><?= $key; ?></td>
                            <td><?php var_dump($value); ?></td>
                        </tr>
                    <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div><!-- End panel content -->
</div><!-- End pdw panel -->
