<div id='pdw-panel-server' class='pdw-panel server'>
    <div class='title'>
        <h2>Server <a class='pdw-panel-close' id="phalcon-debugger-close-server-tab">&times;</a></h2>
    </div>
    <div class='panel-content'>

        <h3 class='collapser'>$_SERVER</h3>

        <table class='pdw-data-table'>
            <tr>
                <th width="30%">Key</th>
                <th>Value</th>
            </tr>
            <?php

            foreach($_SERVER as $k => $v) :
                echo "<tr>";
                    echo "<td>{$k}</td>";
                    echo "<td>{$v}</td>";
                echo "</tr>";
            endforeach;

            ?>
        </table>

        <h3 class='collapser'>Response Headers</h3>

        <table class='pdw-data-table'>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>

            <?php

            $headers = headers_list();
            $headers = !$headers? array() : $headers;

            foreach($headers as $k => $v) :
                echo "<tr>";
                    echo "<td>{$k}</td>";
                    echo "<td>{$v}</td>";
                echo "</tr>";
            endforeach;

            ?>
        </table>
    </div><!-- End panel -->
</div><!-- End pdw panel -->
