<div id='pdw-panel-trace' class='pdw-panel trace'>
    <div class='title'>
        <h2>Trace <a class='pdw-panel-close' id="phalcon-debugger-close-trace-tab">&times;</a></h2>
    </div>
    <div class='panel-content'>
        <?php
        // get the stack as an array
        $profileStack = forp_dump();

        print_r($profileStack);

        ?>
    </div><!-- End panel content -->
</div><!-- End pdw panel -->
