<?php $views = $debugWidget->getRenderedViews(); ?>
<div id='pdw-panel-views' class='pdw-panel views'>
    <div class='title'>
        <h2>Views <a class='pdw-panel-close' id="phalcon-debugger-close-views-tab">&times;</a></h2>
    </div>
    <div class='panel-content'>
        <?php foreach($views as $rendered): ?>
            <h3 class='collapser'><?php echo pathinfo($rendered['path'], PATHINFO_BASENAME); ?></h3>
            <table class='pdw-data-table'>
                <?php foreach($rendered as $k => $v) : $class = ($k == 'params')? "language-php" : ""; ?>
                    <tr>
                        <td width="10%" valign="top"><?= $k; ?></td>
                        <td><pre><code class="<?= $class; ?>"><?php var_dump($v); ?></code></pre></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endforeach; ?>
    </div><!-- End panel content -->
</div><!-- End pdw panel -->
